using System.Collections.Generic;
using System.Globalization;
using System.Text;
using Ediki.Core;

namespace Ediki.Sim
{
    /// <summary>
    /// A read-only tap on a running battle.
    ///
    /// Attached to SimulationConfig, called from the points SimulationRunner
    /// already steps through. It exists so a replay can be produced by the SAME
    /// run loop as a batch instead of a second, simplified one — a transcript
    /// generated by different code would be a description of different code.
    ///
    /// Implementations MUST NOT touch the states they are handed. Nothing here
    /// returns a value, so an observer cannot alter a decision; the remaining way
    /// to break determinism is to mutate a state, and
    /// AttachingAnObserverDoesNotChangeTheBattle guards it.
    /// </summary>
    public interface IBattleObserver
    {
        void RoundStarted(int round, BattleState state);

        /// <summary>One player command, accepted or rejected.</summary>
        void PlayerCommand(int round, BattleState before, ICommand command, ExecuteResult result);

        /// <summary>
        /// Effects produced outside the player's own command loop: the enemy
        /// phase, and the two end-of-turn transitions.
        ///
        /// The enemy side arrives as one log for the whole phase because
        /// EnemyAi.RunFactionTurn owns that loop. Its individual commands — and
        /// so its individual rejections — are not observable from here without
        /// changing Core, which this layer is not allowed to do.
        ///
        /// <paramref name="before"/> is the state the log started from. It is
        /// handed over because effects name units, not places: a hit reported
        /// halfway through a phase belongs to where its victim stood then, and
        /// only the starting state plus the movement effects can say where that was.
        /// </summary>
        void PhaseResolved(int round, Faction phase, BattleState before, EffectLog log, BattleState after);

        /// <summary>
        /// The round is over — both phases have run, or the battle ended inside
        /// one. Fires exactly once per round that was played, including a round
        /// cut short, because the round everything died in is the one worth seeing.
        /// </summary>
        void RoundEnded(int round, BattleState state);

        void BattleFinished(BattleResult result, BattleState finalState);
    }

    /// <summary>
    /// Turns a battle into readable text, one round at a time.
    ///
    /// Everything it prints comes from the existing effect stream (Effects.cs) or
    /// from the state the runner already had in hand. No second action pipeline,
    /// no re-derivation of damage: if the transcript says 40 damage, that is the
    /// HpChanged the rule layer emitted.
    /// </summary>
    public sealed class BattleTranscript : IBattleObserver
    {
        private readonly StringBuilder _sb = new StringBuilder();
        private BattleState _latest;

        public BattleTranscript(string encounter, string strategy, int seed,
                                int noisePercent, int roundCap)
        {
            _sb.Append("=== Replay: ").Append(encounter).Append(" / ").Append(strategy)
               .Append(" / seed ").Append(N(seed)).AppendLine(" ===");
            _sb.Append("noise ").Append(N(noisePercent)).Append("%   round cap ").Append(N(roundCap))
               .AppendLine("   (noise is a sampling device and the cap is a safety net — neither is a rule)");
            _sb.AppendLine();
        }

        public string Text => _sb.ToString();

        /// <summary>Rounds seen. Zero means the battle ended before it began.</summary>
        public int RoundsSeen { get; private set; }

        public void RoundStarted(int round, BattleState state)
        {
            RoundsSeen = round;
            _latest = state;
            _sb.Append("Round ").Append(N(round)).AppendLine();
        }

        public void PlayerCommand(int round, BattleState before, ICommand command, ExecuteResult result)
        {
            _latest = result.State;

            int actorId;
            UnitState actor = TryGetActor(command, out actorId) ? before.FindUnit(actorId) : null;
            AppendActorHeader(before, actor);

            _sb.Append("    Action: ").Append(DescribeAction(before, command));

            if (!result.Ok)
            {
                // A refused command is the single most useful line in a triage
                // transcript, so it is never silently skipped.
                _sb.Append("   REJECTED: ").Append(result.RejectReason ?? "(no reason given)");
                _sb.AppendLine();
                return;
            }

            _sb.AppendLine();
            AppendEffects(result.Log, result.State, "      ");
        }

        public void PhaseResolved(int round, Faction phase, BattleState before, EffectLog log, BattleState after)
        {
            _latest = after;
            if (log == null || log.Count == 0) return;

            _sb.Append("  -- ").Append(phase).AppendLine(" phase");
            AppendEffects(log, after, "    ");
        }

        /// <summary>Nothing to print: every action in the round already has a line.</summary>
        public void RoundEnded(int round, BattleState state) { _latest = state; }

        public void BattleFinished(BattleResult result, BattleState finalState)
        {
            _latest = finalState;
            _sb.AppendLine();
            _sb.Append("=== ").Append(result.Outcome)
               .Append(" after ").Append(N(result.PlayerTurns)).Append(" round(s)")
               .Append(", TurnIndex ").Append(N(result.Turns)).AppendLine(" ===");

            if (result.HitRoundCap)
            {
                _sb.AppendLine("  ** unresolved: the battle was still in progress when the harness stopped");
                if (result.EndedByRejectedCommand)
                    _sb.AppendLine("  ** and it stopped on a REJECTED command, not on the round cap");
            }

            _sb.Append("  player HP ").Append(N(result.FinalPlayerHp)).Append('/').Append(N(result.PlayerMaxHp))
               .Append("   enemies left ").Append(N(result.EnemiesRemaining))
               .Append("   state hash ").Append(result.FinalStateHash.ToString(CultureInfo.InvariantCulture))
               .AppendLine();

            if (result.StrategySkillActions > 0 || result.NoiseSkillActions > 0)
            {
                _sb.Append("  skills: ").Append(N(result.StrategySkillActions)).Append(" by strategy, ")
                   .Append(N(result.NoiseSkillActions)).AppendLine(" by sampling noise");
            }

            foreach (UnitState u in finalState.Units)
            {
                _sb.Append("  ").Append(Label(u)).Append(' ')
                   .Append(u.IsAlive ? "Pos=" + u.Position + " HP=" + N(u.Hp) + "/" + N(u.Def.MaxHp) : "DEAD")
                   .AppendLine();
            }
        }

        // ------------------------------------------------------------ rendering

        private void AppendActorHeader(BattleState before, UnitState actor)
        {
            if (actor == null)
            {
                _sb.AppendLine("  [?] (actor not found)");
                return;
            }

            _sb.Append("  ").Append(Label(actor))
               .Append(" Pos=").Append(actor.Position)
               .Append(" AP=").Append(N(actor.Ap))
               .Append(" HP=").Append(N(actor.Hp)).Append('/').Append(N(actor.Def.MaxHp));
            if (actor.IsGuarding) _sb.Append(" GUARDING");
            if (before.IsSlowed(actor)) _sb.Append(" SLOWED");
            if (before.IsTaunting(actor)) _sb.Append(" TAUNTING");
            _sb.AppendLine();
        }

        /// <summary>
        /// One line per effect, in the causal order the rule layer produced them.
        ///
        /// Effect.Describe() already exists and is used for the shapes that have
        /// no unit to name; the ones a reader actually needs — who moved, who hit
        /// whom for how much — are rendered with names resolved, because "u4" is
        /// not something a person can triage.
        /// </summary>
        private void AppendEffects(EffectLog log, BattleState after, string indent)
        {
            if (log == null) return;

            for (int i = 0; i < log.Count; i++)
            {
                Effect e = log[i];

                if (e is UnitMoved moved)
                {
                    _sb.Append(indent).Append(Label(after, moved.UnitId))
                       .Append(" Move ").Append(moved.From).Append(" -> ").Append(moved.To)
                       .Append("  (").Append(N(moved.Path == null ? 0 : moved.Path.Length)).AppendLine(" steps)");
                }
                else if (e is UnitPushed pushed)
                {
                    _sb.Append(indent).Append(Label(after, pushed.UnitId))
                       .Append(" Pushed ").Append(pushed.From).Append(" -> ").Append(pushed.To)
                       .Append(" by ").AppendLine(Label(after, pushed.ByUnitId));
                }
                else if (e is AttackResolved attack)
                {
                    _sb.Append(indent).Append(Label(after, attack.AttackerId))
                       .Append(" Attack -> ").Append(Label(after, attack.TargetId))
                       .AppendLine(attack.Hit ? "" : "  MISS");
                }
                else if (e is CounterAttacked counter)
                {
                    _sb.Append(indent).Append(Label(after, counter.DefenderId))
                       .Append(" Counter -> ").AppendLine(Label(after, counter.AttackerId));
                }
                else if (e is HpChanged hp)
                {
                    UnitState u = after.FindUnit(hp.UnitId);
                    _sb.Append(indent).Append(hp.Delta < 0 ? "  Damage " : "  Healing ")
                       .Append(N(hp.Delta < 0 ? -hp.Delta : hp.Delta))
                       .Append(" -> ").Append(Label(after, hp.UnitId))
                       .Append(" (HP ").Append(N(hp.NewHp)).Append('/')
                       .Append(N(u == null ? 0 : u.Def.MaxHp)).AppendLine(")");
                }
                else if (e is UnitDied died)
                {
                    _sb.Append(indent).Append("  ").Append(Label(after, died.UnitId)).AppendLine(" DIES");
                }
                else if (e is UnitRested rested)
                {
                    _sb.Append(indent).Append(Label(after, rested.UnitId))
                       .Append(" Rest  +").Append(N(rested.HealAmount)).AppendLine(" HP");
                }
                else if (e is TauntApplied taunt)
                {
                    _sb.Append(indent).Append(Label(after, taunt.UnitId))
                       .Append(" Taunt  radius ").Append(N(taunt.Radius))
                       .Append(" through T").Append(N(taunt.UntilTurn)).AppendLine();
                }
                else if (e is SlowApplied slow)
                {
                    _sb.Append(indent).Append(Label(after, slow.UnitId))
                       .Append(" Slowed through T").Append(N(slow.UntilTurn)).AppendLine();
                }
                else if (e is GuardApplied guard)
                {
                    _sb.Append(indent).Append(Label(after, guard.UnitId))
                       .Append(" Guard  incoming damage ").Append(N(guard.DamagePercent)).AppendLine("%");
                }
                else if (e is UnitSpawned spawned)
                {
                    _sb.Append(indent).Append(Label(after, spawned.UnitId))
                       .Append(" ARRIVES at ").Append(spawned.Position).AppendLine();
                }
                else if (e is BattleEnded ended)
                {
                    _sb.Append(indent).Append("  BATTLE ENDS: ").Append(ended.Outcome).AppendLine();
                }

                // ApSpent / ApReset / TurnStarted / TurnEnded / UnitWaited /
                // GuardExpired / UnitActivated / TerrainContaminated are
                // deliberately not printed: they fire on every single command and
                // would bury the decisions under bookkeeping. The AP that matters
                // is already on the actor header line.
            }
        }

        private string DescribeAction(BattleState before, ICommand command)
        {
            if (command is MoveCommand move)
            {
                Coord last = move.Path != null && move.Path.Length > 0
                    ? move.Path[move.Path.Length - 1] : new Coord(-1, -1);
                return "Move -> " + last + "  (" + N(move.Path == null ? 0 : move.Path.Length) + " steps)";
            }
            if (command is AttackCommand attack) return "Attack -> " + Label(before, attack.TargetId);
            if (command is SlowCommand slow) return "Slow -> " + Label(before, slow.TargetId);
            if (command is PushCommand push) return "Push -> " + Label(before, push.TargetId);
            if (command is TauntCommand) return "Taunt";
            if (command is PurifyCommand) return "Purify";
            if (command is GuardCommand) return "Guard";
            if (command is RestCommand) return "Rest";
            if (command is WaitCommand) return "Wait";
            return command == null ? "(null)" : command.Describe();
        }

        /// <summary>
        /// The acting unit of a command. Commands name that field differently
        /// (UnitId / AttackerId / ActorId) and there is no shared accessor in
        /// Core, so this maps them here rather than adding one to the rule layer.
        /// </summary>
        public static bool TryGetActor(ICommand command, out int unitId)
        {
            unitId = -1;
            if (command is MoveCommand move) { unitId = move.UnitId; return true; }
            if (command is AttackCommand attack) { unitId = attack.AttackerId; return true; }
            if (command is GuardCommand guard) { unitId = guard.UnitId; return true; }
            if (command is RestCommand rest) { unitId = rest.UnitId; return true; }
            if (command is WaitCommand wait) { unitId = wait.UnitId; return true; }
            if (command is TauntCommand taunt) { unitId = taunt.UnitId; return true; }
            if (command is PurifyCommand purify) { unitId = purify.UnitId; return true; }
            if (command is SlowCommand slow) { unitId = slow.ActorId; return true; }
            if (command is PushCommand push) { unitId = push.ActorId; return true; }
            return false;
        }

        private static string Label(BattleState state, int unitId)
        {
            UnitState u = state == null ? null : state.FindUnit(unitId);
            return u == null ? "[?#" + N(unitId) + "]" : Label(u);
        }

        private static string Label(UnitState u) =>
            "[" + u.Faction + ":" + u.Def.DisplayName + " #" + N(u.Id) + "]";

        private static string N(int value) => value.ToString(CultureInfo.InvariantCulture);
    }

    /// <summary>
    /// Runs one battle for inspection.
    ///
    /// It is a thin wrapper on purpose: the whole value of a replay is that it
    /// goes through SimulationRunner.RunOne with the same config and the same
    /// seed the batch used, so there is nothing here that could disagree with it.
    /// </summary>
    public static class ReplayRunner
    {
        public sealed class Result
        {
            public BattleResult Battle;
            public string Transcript;
        }

        public static Result Run(SimulationRunner runner, SimulationConfig config, int seed)
        {
            BattleTranscript transcript = new BattleTranscript(
                config.MapName, config.Strategy.Name, seed, config.NoisePercent, config.MaxRounds);

            // Same config object shape as the batch; only the observer is added,
            // and an observer cannot influence a decision.
            IBattleObserver previous = config.Observer;
            config.Observer = transcript;
            try
            {
                BattleResult battle = runner.RunOne(config, seed);
                return new Result { Battle = battle, Transcript = transcript.Text };
            }
            finally
            {
                config.Observer = previous;
            }
        }
    }
}
