using System;
using System.Collections.Generic;
using System.Text;
using Ediki.Core;

namespace Ediki.Editor.Prototype
{
    /// <summary>
    /// Turns "the planner retyped Momotaro's HP" into a real unit id.
    ///
    /// WHY NOT just edit the existing row (decided 2026-08-18): one units.txt row
    /// is shared by every encounter that names it. Momotaro_B alone is referenced
    /// by the crucible maps that the squad matrix is measured on, so a single
    /// keystroke in an inspector would silently move published numbers in files
    /// nobody had open. Appending a variant leaves every existing row byte-for-byte
    /// intact, which also means the A4 golden constants cannot move.
    ///
    /// It is also what the project already does by hand — Momotaro_A/_B,
    /// Kagemaru_c1..c5, the _g5 rung — and what SquadMatrix does programmatically
    /// when it swaps ids in spawn lines. This is that pattern with the typing
    /// removed, not a new mechanism.
    ///
    /// Plan() is pure so it can be tested; writing the file is the caller's job.
    /// </summary>
    public static class UnitVariantWriter
    {
        public const string SectionHeader = "# --- editor variants (generated by the Prototype Editor) ---";

        public sealed class Plan
        {
            /// <summary>units.txt lines to append, in order. Empty when nothing changed.</summary>
            public readonly List<string> NewUnitLines = new List<string>();

            /// <summary>Spawn index -> the unit id it must be rewritten to.</summary>
            public readonly Dictionary<int, string> SpawnIdRewrites = new Dictionary<int, string>();

            /// <summary>Human-readable summary for the status bar.</summary>
            public readonly List<string> Notes = new List<string>();

            public bool ChangesAnything => NewUnitLines.Count > 0 || SpawnIdRewrites.Count > 0;
        }

        /// <summary>
        /// Resolves every pending stat edit in the document to an id.
        ///
        /// Three outcomes per edited spawn, in order of preference:
        ///   1. the edits reproduce the base unit exactly  -> keep the base id
        ///   2. some other catalog unit already has exactly these numbers
        ///                                                 -> reuse that id
        ///   3. otherwise                                  -> allocate base_vN
        ///
        /// Cases 1 and 2 are what stop the roster growing a row every time
        /// someone types a number and types it back.
        /// </summary>
        public static Plan BuildPlan(EncounterDocument doc, UnitCatalog units, IEnumerable<string> knownIds)
        {
            Plan plan = new Plan();

            HashSet<string> taken = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string id in knownIds) taken.Add(id);

            // Two spawns edited to the same numbers must land on the same id, or
            // the roster grows one row per identical minion.
            Dictionary<string, string> allocated = new Dictionary<string, string>(StringComparer.Ordinal);

            for (int i = 0; i < doc.Spawns.Count; i++)
            {
                SpawnEntry spawn = doc.Spawns[i];
                if (!spawn.HasPendingStats) continue;

                UnitStatBlock stats = spawn.PendingStats;
                string baseId = RootIdOf(spawn.UnitId);

                UnitDef current;
                if (units.TryGet(spawn.UnitId, out current) && stats.MatchesStatsOf(current))
                {
                    plan.Notes.Add(doc.TagOf(spawn) + "：數值和原本一樣，沒有建立新角色。");
                    continue;
                }

                string signature = Signature(baseId, stats);

                string reused;
                if (allocated.TryGetValue(signature, out reused))
                {
                    plan.SpawnIdRewrites[i] = reused;
                    continue;
                }

                string existing = FindMatchingId(stats, units, knownIds);
                if (existing != null)
                {
                    allocated[signature] = existing;
                    plan.SpawnIdRewrites[i] = existing;
                    plan.Notes.Add(doc.TagOf(spawn) + "：數值和既有的「" + existing + "」相同，直接沿用。");
                    continue;
                }

                string newId = AllocateId(baseId, taken);
                taken.Add(newId);
                allocated[signature] = newId;

                plan.SpawnIdRewrites[i] = newId;
                plan.NewUnitLines.Add(stats.ToDataLine(newId));
                plan.Notes.Add(doc.TagOf(spawn) + "：建立新角色「" + newId + "」。");
            }

            return plan;
        }

        /// <summary>
        /// Applies a plan to the document: rewrites ids and clears the pending
        /// edits that the plan accounted for. Call only after the units.txt write
        /// succeeded, so a failed write cannot leave spawns pointing at ids that
        /// were never persisted.
        /// </summary>
        public static void ApplyToDocument(EncounterDocument doc, Plan plan)
        {
            foreach (KeyValuePair<int, string> rewrite in plan.SpawnIdRewrites)
            {
                if (rewrite.Key < 0 || rewrite.Key >= doc.Spawns.Count) continue;
                doc.Spawns[rewrite.Key].UnitId = rewrite.Value;
            }
            for (int i = 0; i < doc.Spawns.Count; i++) doc.Spawns[i].PendingStats = null;
        }

        /// <summary>
        /// The section appended to units.txt. Kept as one block with a header so
        /// a human reading the file can see at a glance which rows a tool wrote.
        /// </summary>
        public static string AppendBlock(string existingText, List<string> newLines)
        {
            StringBuilder sb = new StringBuilder(existingText ?? "");
            if (sb.Length > 0 && sb[sb.Length - 1] != '\n') sb.Append('\n');

            if ((existingText ?? "").IndexOf(SectionHeader, StringComparison.Ordinal) < 0)
                sb.Append('\n').Append(SectionHeader).Append('\n');

            for (int i = 0; i < newLines.Count; i++) sb.Append(newLines[i]).Append('\n');
            return sb.ToString();
        }

        // ---------------------------------------------------------- internals

        /// <summary>
        /// Strips a trailing _vN so editing a variant twice gives base_v2, not
        /// base_v1_v1. Anything else in the id is left alone — _A, _B, _g5 and
        /// _c3 are hand-authored rungs and must not be treated as generated.
        /// </summary>
        public static string RootIdOf(string id)
        {
            if (string.IsNullOrEmpty(id)) return "unit";

            int i = id.Length - 1;
            while (i >= 0 && id[i] >= '0' && id[i] <= '9') i--;
            if (i < 1 || i == id.Length - 1) return id;
            if (id[i] != 'v' || id[i - 1] != '_') return id;
            return id.Substring(0, i - 1);
        }

        private static string AllocateId(string baseId, HashSet<string> taken)
        {
            for (int n = 1; n < 10000; n++)
            {
                string candidate = baseId + "_v" + n;
                if (!taken.Contains(candidate)) return candidate;
            }
            return baseId + "_v" + Guid.NewGuid().ToString("N").Substring(0, 6);
        }

        private static string FindMatchingId(UnitStatBlock stats, UnitCatalog units, IEnumerable<string> knownIds)
        {
            foreach (string id in knownIds)
            {
                UnitDef def;
                if (!units.TryGet(id, out def)) continue;
                if (stats.MatchesStatsOf(def)) return id;
            }
            return null;
        }

        private static string Signature(string baseId, UnitStatBlock s)
        {
            return baseId + "|" + s.ToDataLine("_");
        }
    }
}
